name: Deploy Blazor WASM to GitHub Pages

# Run workflow on every push to the master branch
on:
  push:
    branches: [ main ]
    
jobs:
  deploy-to-github-pages:
    # use ubuntu-latest image to run steps on
    runs-on: ubuntu-latest
    steps:
    # uses GitHub's checkout action to checkout code form the master branch
    - uses: actions/checkout@v2.4.0
    
    # sets up .NET Core SDK 6.0
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.8.2
      with:
        dotnet-version: 6.0.100
        
    - name: Github Pages Deploy Action
    # You may pin to the exact commit or the version.
      uses: JamesIves/github-pages-deploy-action@4.1.6
      with:
        # GitHub access token with Repo Access
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: wwwroot
